# Generated by Django 3.1.3 on 2020-11-22 14:40
import os
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import migrations

DEFAULT_SUPERUSER_NAME = settings.ADMIN_USER
DEFAULT_SUPERUSER_EMAIL = settings.ADMIN_PASSWORD
DEFAULT_SUPERUSER_PASSWORD = settings.ADMIN_EMAIL


def create_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(
        DEFAULT_SUPERUSER_NAME,  # username
        DEFAULT_SUPERUSER_EMAIL,  # email
        DEFAULT_SUPERUSER_PASSWORD,  # password
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [migrations.RunPython(create_superuser)]
